server:
  port: 8761

spring:
  application:
    name: ebuy-registry-service

eureka:
  instance:
    hostname: registry
    preferIpAddress: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://ebuy-registry-service.herokuapp.com/eureka
    healthcheck:
      enabled: true


