server:
  port: 8761

spring:
  application:
    name: ebuy-registry-service

eureka:
  instance:
    hostname: registry
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${APP_NAME}:8761/eureka/
    healthcheck:
      enabled: true

